# Generated by Django 4.2.17 on 2025-01-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=222)),
                ('emial', models.EmailField(max_length=222)),
                ('phone', models.IntegerField(max_length=222)),
            ],
        ),
    ]
